"""make 3 tables

Revision ID: 6f395df25483
Revises: 
Create Date: 2024-12-17 14:14:28.990912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f395df25483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    candidates = op.create_table('candidates',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id'),
    sa.UniqueConstraint('name')
    )
    users = op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mail')
    )
    votes = op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    # Insert initial data into users table
    op.bulk_insert(
        users,
        [
            {'user_id': 1, 'mail': 'admin@mail.com', 'password': 'scrypt:32768:8:1$HGLCBcceSpZNaKFY$b7274e7e12204a4fe3709605b0800d6d4327351075582cc4be7128e23412a1937f2682cf7ee18f5858d07eabd334dd2e629e377fbf7934d77d5360faf25eff29'},
            {'user_id': 2, 'mail': 'user@mail.com', 'password': 'scrypt:32768:8:1$z9dyksZCi4Rmls5n$9b374bd104a6be9212f00356ef2b3dc62976e227915948939ab1fa312d09b11f787d73b38b9a95de42d3e7fb2602568ce5c1c4d4174789d071b8699edb4d7a09'}
        ]
    )

    # Insert initial data into candidates table
    op.bulk_insert(
        candidates,
        [
            {'candidate_id': 1, 'name': 'Joko Winarna', 'votes': 0, 'description': 'Dikenal sebagai bapak pembangunan di kelurahan nusantara'},
            {'candidate_id': 2, 'name': 'Prabawi Subianta', 'votes': 0, 'description': 'Merupakan lulusan terbaik dari akademi militer tahun 2019'},
            {'candidate_id': 3, 'name': 'Fufufafa', 'votes': 1, 'description': 'Namanya sangat dikenal seluruh warga kelurahan nusantara'}
        ]
    )

    # Insert initial data into votes table
    op.bulk_insert(
        votes,
        [
            {'vote_id': 1, 'user_id': 1, 'candidate_id': 3}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_table('users')
    op.drop_table('candidates')
    # ### end Alembic commands ###
