"""create 3 tables

Revision ID: f471ecb2a827
Revises: 
Create Date: 2024-12-17 15:00:57.210882

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = 'f471ecb2a827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    events = op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    users = op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('quota', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('mail')
    )
    bookings = op.create_table('bookings',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.bulk_insert(users, [
        {'user_id': 1, 'mail': 'admin@mail.com', 'password': 'scrypt:32768:8:1$HGLCBcceSpZNaKFY$b7274e7e12204a4fe3709605b0800d6d4327351075582cc4be7128e23412a1937f2682cf7ee18f5858d07eabd334dd2e629e377fbf7934d77d5360faf25eff29', 'quota': 2},
        {'user_id': 2, 'mail': 'user@mail.com', 'password': 'scrypt:32768:8:1$z9dyksZCi4Rmls5n$9b374bd104a6be9212f00356ef2b3dc62976e227915948939ab1fa312d09b11f787d73b38b9a95de42d3e7fb2602568ce5c1c4d4174789d071b8699edb4d7a09', 'quota': 3},
    ])
    op.bulk_insert(events, [
        {'event_id': 1, 'event_title': 'PyCon APAC 2024', 'description': 'Python Conference Asia Pacific 2024 in Yogyakarta', 'location': 'Yogyakarta, Indonesia', 'date': datetime.date(2024, 11, 25), 'participants': 1},
        {'event_id': 2, 'event_title': 'PyCon Indonesia 2023', 'description': 'Python Conference Indonesia 2023 in Bandung', 'location': 'Bandung, Indonesia', 'date': datetime.date(2023, 10, 25), 'participants': 0},
        {'event_id': 3, 'event_title': 'Python Jogja December Meetup', 'description': 'Python Jogja Meetup Lightning Talk', 'location': 'Universitas Teknologi Yogyakarta', 'date': datetime.date(2024, 12, 27), 'participants': 0},
    ])
    op.bulk_insert(bookings, [
        {'vote_id': 1, 'user_id': 1, 'event_id': 1},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('users')
    op.drop_table('events')
    # ### end Alembic commands ###
